version: '3.8'
services:
  freeswitch:
    image: drachtio/drachtio-freeswitch-mrf:latest
    container_name: stoppai_freeswitch
    network_mode: host
    restart: always
    volumes:
      - ./config:/usr/local/freeswitch/conf
      - ./recordings:/recordings
    environment:
      - TZ=Europe/Rome
