[general]
static=yes
writeprotect=no

[default]
exten => _.,1,NoOp(ARIA)
exten => _.,2,Answer()
exten => _.,3,Wait(1)
exten => _.,4,Playback(silence/1)
exten => _.,5,Playback(/var/lib/asterisk/sounds/it/benvenuto)
exten => _.,6,Wait(1)
exten => _.,7,Playback(/var/lib/asterisk/sounds/it/beep)
exten => _.,8,Wait(1)
exten => _.,9,MixMonitor(/opt/stoppai/asterisk/recordings/msg_${CALLERID(num)}_${EPOCH}.wav)
exten => _.,10,Wait(20)
exten => _.,11,StopMixMonitor()
exten => _.,12,Playback(vm-goodbye)
exten => _.,13,Hangup()
