[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0
external_signaling_address=46.225.14.90
external_media_address=46.225.14.90

[opensolution-reg]
type=registration
transport=transport-udp
outbound_auth=opensolution-auth
server_uri=sip:sip.opensolution.it
client_uri=sip:504211898065@sip.opensolution.it
contact_user=504211898065
retry_interval=30
expiration=120

[opensolution-auth]
type=auth
auth_type=userpass
password=Ifs04211898065!pass
username=504211898065

[opensolution-aor]
type=aor
contact=sip:sip.opensolution.it:5060
qualify_frequency=15

[opensolution-endpoint]
type=endpoint
context=default
disallow=all
allow=alaw
allow=ulaw
outbound_auth=opensolution-auth
aors=opensolution-aor
direct_media=no
rewrite_contact=yes
force_rport=yes

[opensolution-identify]
type=identify
endpoint=opensolution-endpoint
match=sip.opensolution.it
