[general]
context=default
bindport=5060
bindaddr=0.0.0.0
transport=udp
language=it
externip=46.225.14.90
localnet=172.16.0.0/12
disallow=all
allow=ulaw
allow=alaw
allow=g729

[opensolution]
type=peer
host=sip.opensolution.it
port=5060
username=504211898065
secret=Ifs04211898065!pass
fromuser=504211898065
fromdomain=sip.opensolution.it
insecure=invite,port
qualify=yes
nat=force_rport,comedia
dtmfmode=rfc2833
disallow=all
allow=ulaw
allow=alaw
allow=g729
