[general]
static=yes
writeprotect=no

[default]
exten => _.,1,NoOp(ARIA)
exten => _.,2,Answer()
exten => _.,3,Wait(1)
exten => _.,4,Playback(silence/1)
exten => _.,5,MixMonitor(/opt/stoppai/asterisk/recordings/msg.wav)
exten => _.,6,Playback(/var/lib/asterisk/sounds/it/benvenuto)
exten => _.,7,Wait(1)
exten => _.,8,Playback(/var/lib/asterisk/sounds/it/beep)
exten => _.,9,Wait(20)
exten => _.,10,StopMixMonitor()
exten => _.,11,Playback(vm-goodbye)
exten => _.,12,Hangup()
