[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[opensolution-auth]
type=auth
auth_type=userpass
username=504211898065
password=Ifs04211898065!pass

[opensolution-aor]
type=aor
contact=sip:sip.opensolution.it:5060
qualify_frequency=30

[opensolution-reg]
type=registration
transport=transport-udp
outbound_auth=opensolution-auth
server_uri=sip:sip.opensolution.it
client_uri=sip:504211898065@sip.opensolution.it
contact_user=504211898065
retry_interval=30
expiration=120

[opensolution]
type=endpoint
transport=transport-udp
context=default
disallow=all
allow=alaw
allow=ulaw
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
rtp_keepalive=5
ice_support=no
aors=opensolution-aor
outbound_auth=opensolution-auth

[opensolution-identify]
type=identify
endpoint=opensolution
match=sip.opensolution.it
match=77.239.128.7
